### ISSUE TITLE
modular dependency @imports

### ISSUE THREAD

**Issue by jasonbellamy** [plum-css/plum#3]
I was thinking we should include  (@import) all dependencies needed in a module, unit, page, etc instead of relying on these configurations being set globally in an `exports/` file. This should allow PLUM to be integrated into more modular systems with webpack, etc, without straying from the underlying methodology.

**Comment by himynameisdave** [comment]
So in practice something like this:

```
|- dependencies/
   |- dependency.scss
|- modules/
   |- module-1.scss    <-- @imports dependency.scss
   |- module-2.scss    <-- also @imports dependency.scss 
```

I'm actually not sure just curious, but will we have duplications in the code if we're importing the same dep more than once? Are we still going to have a main file under `exports` that imports all the modules into a single file?

I think it makes sense as a concept though because then when you're working on a module you'll know exactly what it's dependant on. Also in the future it will be easier to rip out a component and use it in another project because you'll know exactly what that component needs.

**Comment by jasonbellamy** [comment]
I was thinking a structure along the lines of:

```
├── modules
│   └── module
│       ├── _index.scss
│       ├── partials
│       │   ├── _base.scss
│       │   ├── _layout.scss
│       │   ├── _modifier.scss
│       │   ├── _state.scss
│       │   └── _theme.scss
│       └── tests
│           ├── baselines
│           │   └── module.png
│           ├── fixtures
│           │   └── module.hbs
│           └── index.js
└── units
    └── unit
        ├── _index.scss
        └── tests
            ├── baselines
            │   └── unit.png
            ├── fixtures
            │   └── unit.hbs
            └── index.js
```

``` scss
// modules/module/_index.scss
@import "partials/base";
@import "partials/layout";
@import "partials/modifier";
@import "partials/state";
@import "partials/theme";
```

``` scss
// units/unit/_index.scss
@import "/configs/default/index";
@import "/modules/module/index";
```

This above architecture allows us to use the "unit" freely whether its in export files:

``` scss
// exports/export.scss
@import "/units/unit/index"; // traces and pulls in modules& configs
```

page files:

``` scss
// pages/_page.scss
@import "/units/unit/index"; // traces and pulls in modules & configs
```

or even being including in a JavaScript file via webpack:

``` javascript
var unit = require("css!/units/unit/index");  // traces and pulls in modules & configs
```

Since every file declaratively declares its dependencies we can be sure that when we include the "unit" we're also always getting all of its dependencies as well.

**Comment by jasonbellamy** [comment]
As for duplication in the code, that should not be an issue, with most build tools. This structure should actually gives us more flexibility.  

Since we've declaratively set all of the dependencies for the unit above, we could compile that down into a `unit.css` file if we wanted to and only serve (then cache) that file as its needed on a site.

**Comment by jasonbellamy** [comment]
Cosed via https://github.com/plum-css/generator-plum/pull/12

Thanks @himynameisdave
